apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kn0l52fpz-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kn0l52fpz-python 
  name: kn0l52fpz-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: kn0l52fpz-python 
